### ISSUE TITLE
New parameter REPIN-RAYT distance

### ISSUE THREAD

**Issue by CFGrote** [mpievolbio-scicomp/rarefan#20]
@fredeBio added a new parameter to the java backengine to control the association distance between REPINs and RAYTs. This must now be exposed to the submitting user in the web interface.

## TODOs
- [x] Merge branch frederic into develop
- [x] Branch out to this issue's branch
- [x] Test java CLI (maybe adjust default handling)
- [x] Add new parameter to python CLI
- [x] Test python CLI
- [x] Add parameter to model and database
- [x] Legacy support
- [x] Adjust submit html template
- [x] Adjust submit route
- [x] Test various cases

**Comment by CFGrote** [comment]
hard coded value was 200, see https://github.com/mpievolbio-scicomp/rarefan/commit/d7fbbf75f161e764e7b2832e72c9dc9f4b0de631#commitcomment-89124536
